// writeups.js - WRITEUPS METADATA
/*
  {
    id:         "",
    title:      "",
    category:   "",            // htb | tryhackme | ctf | vulnhub | pico
    platform:   "",
    os:         "",            // Linux | Windows | "empty"
    difficulty: "",            // Easy | Medium | Hard | Insane
    date:       "",
    author:     "",            // or "" for local
    image:      "",
    locked:     false          // true = not open
    excerpt:    "",
    tags:       []             // topics/tech usados, ej: ["kerberos","xss","rce"]
  },
*/

const WRITEUPS = [
  {
    id:         "two-million",
    title:      "HackTheBox: TwoMillion",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "May 10, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/twomillion/01_logo.png",
    locked:     false,
    excerpt:    "TwoMillion is an Easy difficulty Linux box released to celebrate 2 million HackTheBox users. It features the old HTB platform with a hackable invite code, API role escalation via IDOR, command injection in the admin VPN endpoint, plaintext credentials in a .env file, and privilege escalation via CVE-2023-0386 (OverlayFS kernel exploit).",
    tags:       ["javascript", "api", "idor", "command-injection", "env-file", "credential-reuse", "kernel-exploit", "overlayfs", "cve"]
  },
  {
    id:         "danglingtree",
    title:      "HackTheBox: DanglingTree",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Windows",
    difficulty: "Medium",
    date:       "Aug 09, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/danglingtree/01_logo.png",
    locked:     true,
    excerpt:    "DanglingTree is a Medium difficulty Windows machine chaining WAC remote privilege escalation (CVE-2026-26119), SmarterMail auth bypass (WT-2026-0001), .NET DLL reverse engineering for credential decryption, DPAPI cmdkey abuse, ForceChangePassword, and a novel ADCS attack: creating a dangling ESC1 certificate template via LDAP to exploit an already-published CA name and obtain the Administrator NTLM hash via PKINIT.",
    tags:       ["smb", "guest-share", "wac", "cve", "rce", "smartermail", "wt-2026-0001", "auth-bypass", "port-forwarding", "dotnet", "dll-reversing", "hardcoded-key", "runascs", "dpapi", "cmdkey", "forcechangepassword", "bloodyad", "adcs", "esc1", "dangling-templates", "ldap", "certipy", "pkinit", "strong-certificate-mapping", "ntlm", "active-directory"]
  },
  {
    id:         "cohort",
    title:      "HackTheBox: Cohort",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Aug 01, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/cohort/01_logo.png",
    locked:     true,
    excerpt:    "Cohort is an Easy difficulty Linux machine featuring a data analytics portal with SSRF in its source registration endpoint. Decimal IP bypass reveals internal services including a Marimo notebook server vulnerable to unauthenticated RCE via WebSocket (CVE-2026-39987). Root is achieved by exploiting a TOCTOU race condition in PackageKit via the Pack2TheRoot exploit (CVE-2026-41651).",
    tags:       ["ssrf", "ip-bypass", "internal-discovery", "marimo", "websocket", "rce", "packagekit", "toctou", "race-condition", "lpe", "pack2theroot", "cve"]
  },
  {
    id:         "darkzeroreturns",
    title:      "HackTheBox: DarkZeroReturns",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Windows",
    difficulty: "Hard",
    date:       "Jul 26, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/darkzeroreturns/01_logo.png",
    locked:     true,
    excerpt:    "DarkZeroReturns is a Hard difficulty machine combining Linux/Gitea with a dual-forest Active Directory environment. The chain spans Handlebars SSTI for RCE, bcrypt credential cracking, a Gitea Actions notifier bug (CVE-2026-22555) for CI/CD abuse as svc-runner, CREATE_CHILD + ksu for local root, and an inter-forest golden ticket with extra-SID injection granting SeBackupPrivilege to DCSync darkzero.htb and capture the Administrator flag.",
    tags:       ["ssti", "handlebars", "nodejs", "rce", "mysql", "bcrypt", "kerberos", "ccache", "gitea", "gitea-actions", "ci-cd", "cve", "active-directory", "create-child", "ksu", "bloodyad", "chisel", "socks", "golden-ticket", "extra-sid", "forest-trust", "sebackupprivilege", "dcsync", "pass-the-hash", "impacket"]
  },
  {
    id:         "connected",
    title:      "HackTheBox: Connected",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jul 25, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/connected/01_logo.png",
    locked:     true,
    excerpt:    "Connected is an Easy difficulty Linux machine hosting FreePBX 16.0.40.7. Initial access exploits an unauthenticated SQL injection in the Endpoint Manager module (CVE-2025-57819) chained into RCE via cron_jobs table write. Root is achieved by poisoning /etc/dahdi/init.conf — owned by asterisk — which is sourced by a root script triggered through an incron file-watch on the asterisk spool directory.",
    tags:       ["freepbx", "voip", "asterisk", "sqli", "auth-bypass", "rce", "cron-jobs", "incron", "file-watch", "config-poisoning", "source-injection", "cve"]
  },
  {
    id:         "helix",
    title:      "HackTheBox: Helix",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Medium",
    date:       "Jul 23, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/helix/01_logo.png",
    locked:     false,
    excerpt:    "Helix is a Medium difficulty Linux machine combining industrial automation with data pipeline exploitation. Initial access abuses Apache NiFi's H2 JDBC URL code injection (CVE-2023-34468) to get a reverse shell. Privilege escalation manipulates an OPC-UA industrial server via python-asyncua to push reactor parameters into a maintenance window, triggering helixsvc to enable a root sudo command.",
    tags:       ["apache-nifi", "h2-jdbc", "code-injection", "rce", "opc-ua", "ics", "scada", "asyncua", "industrial", "sudo", "daemon-abuse", "cve"]
  },
  {
    id:         "orion",
    title:      "HackTheBox: Orion",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jul 16, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/orion/01_logo.png",
    locked:     false,
    excerpt:    "Orion is an Easy difficulty Linux machine hosting a CraftCMS 5.6.16 instance vulnerable to unauthenticated PHP deserialization (CVE-2025-32432), achieving RCE. Credentials extracted from config files expose database hashes, and privilege escalation abuses an authentication bypass in GNU inetutils telnetd 2.7 (CVE-2026-24061) via USER environment variable manipulation.",
    tags:       ["craftcms", "deserialization", "php", "rce", "mysql", "telnetd", "auth-bypass", "port-forwarding", "cve"]
  },
  {
    id:         "bedside",
    title:      "HackTheBox: Bedside",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Medium",
    date:       "Jul 19, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/bedside/01_logo.png",
    locked:     true,
    excerpt:    "Bedside is a Medium difficulty Linux machine built around a medical research PDF processing pipeline. Initial access abuses pdfminer.six insecure pickle deserialization (CVE-2025-64512) via a crafted PDF upload. Lateral movement exploits a path traversal in esm.sh (CVE-2025-59341) to steal an SSH private key. Root is achieved by planting a malicious PyTorch checkpoint that executes arbitrary code via torch.load() under a sudo rule.",
    tags:       ["vhost-fuzzing", "pdfminer", "pickle", "deserialization", "rce", "lfi", "path-traversal", "ssh", "pytorch", "torch-load", "sudo", "nosuid", "cve"]
  },
  {
    id:         "makesense",
    title:      "HackTheBox: MakeSense",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Medium",
    date:       "Jul 11, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/makesense/01_logo.png",
    locked:     true,
    excerpt:    "MakeSense is a Medium difficulty Linux machine chaining a hardcoded AES-GCM key in client-side JavaScript, stored XSS in WordPress post metadata, and CSRF to escalate to admin. RCE is achieved via malicious plugin upload, and root is gained by exploiting insecure Tesseract OCR processing with a heredoc injection for arbitrary file write.",
    tags:       ["wordpress", "aes-gcm", "javascript", "stored-xss", "csrf", "rce", "plugin-upload", "ocr", "tesseract", "file-write", "privesc"]
  },
  {
    id:         "paperwork",
    title:      "HackTheBox: Paperwork",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jul 11, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/paperwork/01_logo.png",
    locked:     true,
    excerpt:    "Paperwork is an Easy difficulty Linux machine themed around network printing and document archiving. A static web portal exposes an onboarding document with plaintext root credentials, granting direct SSH access as root. A custom LPD service with a downloadable processor binary serves as a deliberate decoy.",
    tags:       ["lpd", "enumeration", "plaintext-credentials", "credential-reuse", "ssh", "osint", "rabbit-hole"]
  },
  {
    id:         "reactor",
    title:      "HackTheBox: Reactor",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jul 02, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/reactor/01_logo.png",
    locked:     true,
    excerpt:    "Reactor is an Easy difficulty Linux machine hosting a Next.js 15.0.3 application vulnerable to unauthenticated RCE via React Server Components (CVE-2025-55182). Credentials extracted from a SQLite database lead to SSH access, and privilege escalation abuses a Node.js V8 Inspector process running as root via SSH port forwarding.",
    tags:       ["nextjs", "rce", "react-server-components", "sqlite", "ssh", "port-forwarding", "nodejs", "v8-inspector", "cve"]
  },
  {
    id:         "enigma",
    title:      "HackTheBox: Enigma",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jul 02, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/enigma/01_logo.png",
    locked:     true,
    excerpt:    "Enigma is an Easy difficulty Linux machine simulating a corporate environment. An exposed NFS share leaks onboarding credentials, which chain through Roundcube webmail and OpenSTAManager (CVE-2026-38751) to achieve RCE. Privilege escalation abuses OliveTin via command injection through its gRPC-Web API.",
    tags:       ["nfs", "credential-reuse", "roundcube", "openstamanager", "file-upload", "rce", "bcrypt", "grpc", "olivetin", "command-injection", "cve"]
  },
  {
    id:         "cctv",
    title:      "HackTheBox: CCTV",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jun 28, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/cctv/01_logo.png",
    locked:     false,
    excerpt:    "CCTV is an Easy difficulty Linux machine hosting a ZoneMinder instance vulnerable to blind SQL injection (CVE-2024-51482). Credentials extracted from the database lead to RCE via command injection in a misconfigured motionEye service running as root.",
    tags:       ["sqli", "blind-sqli", "zoneminder", "motioneye", "command-injection", "rce", "cve"]
  },
  {
    id:         "kobold",
    title:      "HackTheBox: Kobold",
    category:   "htb",
    platform:   "HackTheBox",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Jun 28, 2026",
    author:     "Ch4rum",
    image:      "writeups/htb/src/kobold/01_logo.png",
    locked:      false,
    excerpt:    "Kobold is an Easy difficulty Linux machine built around AI tooling infrastructure. Initial foothold exploits an unauthenticated RCE in MCPJam Inspector via a crafted MCP server payload (CVE-2026-23744). Privilege escalation abuses Docker group membership to mount the host filesystem and read the root flag.",
    tags:       ["vhost-fuzzing", "mcp", "command-injection", "rce", "docker", "docker-escape", "cve"]
  },
  {
    id:         "library",
    title:      "TryHackMe: Library",
    category:   "thm",
    platform:   "TryHackMe",
    os:         "Linux",
    difficulty: "Easy",
    date:       "Aug 12, 2026",
    author:     "Ch4rum",
    image:      "writeups/thm/src/library/01_logo.png",
    locked:     false,
    excerpt:    "Library is an Easy difficulty Linux room from TryHackMe created for the FIT and BSides Guatemala CTF. A username is discovered through web enumeration and robots.txt hints at rockyou.txt for SSH brute-forcing. Privilege escalation abuses a sudo rule allowing execution of a user-writable Python script as root.",
    tags:       ["enumeration", "robots.txt", "hydra", "ssh-bruteforce", "sudo", "python", "script-abuse", "lpe"]
  },
];